'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { ConvexHttpClient } from 'convex/browser';
import { makeFunctionReference } from 'convex/server';
import { Activity, AlertTriangle, BarChart3, BatteryCharging, Bell, Bolt, CalendarDays, Clock3, Download, Gauge, History, MapPin, Menu, PlugZap, RefreshCw, Settings, SlidersHorizontal, Zap } from 'lucide-react';
import { Area, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Button } from '@/components/ui/button';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';

const CONVEX_URL = 'https://tacit-sockeye-685.eu-west-1.convex.cloud';
const STATIONS = [73151, 72182];
const COLORS = ['#13a874', '#ff8a34', '#1680e8', '#e8474d'];
const historyQuery = makeFunctionReference<'query'>('stations:history');
const latestQuery = makeFunctionReference<'query'>('stations:latest');
type Snapshot = { _id: string; stationId: number; connectorId: string; evseId: string; state: string; rawState: string; checkedAt: number; name: string; address: string };
type Status = 'available' | 'occupied' | 'unavailable' | 'unknown';
const statusOf = (raw = ''): Status => { const value = raw.toUpperCase(); if (value === 'AVAILABLE') return 'available'; if (['BUSY', 'OCCUPIED', 'CHARGING', 'PREPARING', 'FINISHING', 'SUSPENDEDEV', 'SUSPENDEDEVSE'].includes(value)) return 'occupied'; if (['UNAVAILABLE', 'FAULTED', 'OUTOFORDER', 'OUT_OF_ORDER'].includes(value)) return 'unavailable'; return 'unknown'; };
const connectorKey = (row: Snapshot) => `${row.stationId}-${row.connectorId}`;
const stationLabel = (id: number) => id === 73151 ? 'Ultra 1' : 'Ultra 2';
const fmtDate = (ms: number, withDate = true) => new Intl.DateTimeFormat('sk-SK', { timeZone: 'Europe/Bratislava', ...(withDate ? { day: 'numeric', month: 'numeric', year: 'numeric' } : {}), hour: '2-digit', minute: '2-digit' }).format(ms);
const fmtDuration = (ms: number) => { const mins = Math.max(1, Math.round(ms / 60000)); return mins < 60 ? `${mins} min` : `${Math.floor(mins / 60)} h ${mins % 60} min`; };
const dateInput = (date: Date) => date.toISOString().slice(0, 10);

function StatusPill({ status }: { status: Status }) { const labels = { available: 'Voľný', occupied: 'Obsadený', unavailable: 'Nedostupný', unknown: 'Neznámy' }; return <span className={`status status-${status}`}>{labels[status]}</span>; }
function Metric({ icon: Icon, tone, label, value, note }: { icon: typeof Gauge; tone: string; label: string; value: string; note: string }) { return <article className="metric-card"><span className="metric-icon" style={{ '--tone': tone } as React.CSSProperties}><Icon /></span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></article>; }

export default function Home() {
  const [rows, setRows] = useState<Snapshot[]>([]), [latest, setLatest] = useState<Snapshot[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const [station, setStation] = useState('all'), [status, setStatus] = useState('all'), [from, setFrom] = useState(dateInput(new Date(Date.now() - 24 * 3600_000))), [to, setTo] = useState(dateInput(new Date())), [mobileNav, setMobileNav] = useState(false);
  const load = useCallback(async () => { try { const client = new ConvexHttpClient(CONVEX_URL); const [current, ...history] = await Promise.all([client.query(latestQuery, {}), ...STATIONS.map(stationId => client.query(historyQuery, { stationId, limit: 1000 }))]) as [Snapshot[], ...Snapshot[][]]; setLatest(current); setRows(history.flat().sort((a, b) => a.checkedAt - b.checkedAt)); setError(''); } catch { setError('Dáta sa nepodarilo načítať. Skús obnoviť stránku.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); const timer = setInterval(load, 60_000); return () => clearInterval(timer); }, [load]);
  useEffect(() => {
    type Tool = { name: string; title: string; description: string; inputSchema: object; annotations: { readOnlyHint: boolean; untrustedContentHint: boolean }; execute: (input: unknown) => unknown };
    type ModelContext = { registerTool: (tool: Tool, options: { signal: AbortSignal }) => void | Promise<void> };
    const context = (document as Document & { modelContext?: ModelContext }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    void Promise.resolve(context.registerTool({
      name: 'set_report_filters', title: 'Nastaviť filtre reportu',
      description: 'Nastaví viditeľné filtre stanice, stavu a dátumov v ChargeWatch reporte.',
      inputSchema: { type: 'object', properties: { station: { type: 'string', enum: ['all','73151','72182'] }, status: { type: 'string', enum: ['all','available','occupied','unavailable','unknown'] }, from: { type: 'string', format: 'date' }, to: { type: 'string', format: 'date' } }, additionalProperties: false },
      annotations: { readOnlyHint: false, untrustedContentHint: false },
      execute(input) { const value = input as { station?: string; status?: string; from?: string; to?: string }; if (value.station) setStation(value.station); if (value.status) setStatus(value.status); if (value.from) setFrom(value.from); if (value.to) setTo(value.to); return { station: value.station ?? station, status: value.status ?? status, from: value.from ?? from, to: value.to ?? to }; },
    }, { signal: lifecycle.signal })).catch(() => undefined);
    return () => lifecycle.abort();
  }, [station, status, from, to]);
  const filtered = useMemo(() => { const start = new Date(`${from}T00:00:00+02:00`).getTime(), end = new Date(`${to}T23:59:59+02:00`).getTime(); return rows.filter(row => row.checkedAt >= start && row.checkedAt <= end && (station === 'all' || row.stationId === Number(station)) && (status === 'all' || statusOf(row.rawState) === status)); }, [rows, from, to, station, status]);
  const currentRows = useMemo(() => latest.filter(row => station === 'all' || row.stationId === Number(station)), [latest, station]);
  const changes = useMemo(() => { const result: Array<{ row: Snapshot; before: Status; after: Status; duration: number }> = [], byConnector = new Map<string, Snapshot[]>(); filtered.forEach(row => byConnector.set(connectorKey(row), [...(byConnector.get(connectorKey(row)) || []), row])); byConnector.forEach(items => items.forEach((row, i) => { if (i && statusOf(items[i - 1].rawState) !== statusOf(row.rawState)) result.push({ row, before: statusOf(items[i - 1].rawState), after: statusOf(row.rawState), duration: row.checkedAt - items[i - 1].checkedAt }); })); return result.sort((a, b) => b.row.checkedAt - a.row.checkedAt); }, [filtered]);
  const sessions = useMemo(() => changes.filter(c => c.before === 'occupied' && c.after !== 'occupied').map(c => c.duration), [changes]);
  const occupied = filtered.filter(r => statusOf(r.rawState) === 'occupied').length, unavailable = filtered.filter(r => statusOf(r.rawState) === 'unavailable').length, usable = filtered.filter(r => ['available', 'occupied'].includes(statusOf(r.rawState))).length, freeNow = currentRows.filter(r => statusOf(r.rawState) === 'available').length;
  const occupancy = usable ? occupied / usable : 0, unavailability = filtered.length ? unavailable / filtered.length : 0, avgSession = sessions.length ? sessions.reduce((a, b) => a + b, 0) / sessions.length : 0;
  const chartData = useMemo(() => { const buckets = new Map<number, Record<string, number | string>>(); filtered.forEach(row => { const t = Math.floor(row.checkedAt / 300_000) * 300_000, item = buckets.get(t) || { t, label: fmtDate(t, false) }; item[connectorKey(row)] = statusOf(row.rawState) === 'occupied' ? 1 : statusOf(row.rawState) === 'available' ? 0 : 0.5; buckets.set(t, item); }); return [...buckets.values()].slice(-500); }, [filtered]);
  const connectorKeys = useMemo(() => [...new Set(rows.map(connectorKey))].sort(), [rows]);
  const heatmap = useMemo(() => Array.from({ length: 7 }, (_, day) => Array.from({ length: 24 }, (_, hour) => { const samples = filtered.filter(r => { const d = new Date(r.checkedAt); return (d.getDay() + 6) % 7 === day && d.getHours() === hour; }); return samples.length ? samples.filter(r => statusOf(r.rawState) === 'occupied').length / samples.length : null; })), [filtered]);
  const exportCsv = () => { const header = ['checkedAt','stationId','connectorId','evseId','status','rawState','name','address']; const body = filtered.map(r => [new Date(r.checkedAt).toISOString(), r.stationId, r.connectorId, r.evseId, statusOf(r.rawState), r.rawState, r.name, r.address]); const csv = [header, ...body].map(line => line.map(v => `"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); a.download = `chargewatch-${from}-${to}.csv`; a.click(); URL.revokeObjectURL(a.href); };
  const nav = [{ icon: BarChart3, label: 'Prehľad', active: true }, { icon: MapPin, label: 'Stanice' }, { icon: History, label: 'História meraní' }, { icon: Bell, label: 'Upozornenia' }, { icon: Settings, label: 'Nastavenia' }], days = ['Pon','Uto','Str','Štv','Pia','Sob','Ned'];
  return <div className="app-shell"><aside className={`sidebar ${mobileNav ? 'sidebar-open' : ''}`}><div className="brand"><span><Bolt /></span>ChargeWatch</div><nav>{nav.map(({ icon: Icon, label, active }) => <button key={label} className={active ? 'active' : ''}><Icon />{label}</button>)}</nav><div className="eco"><Zap /><span>Čistejšia mobilita<br/>pre krajšie zajtrajšky.</span></div></aside>
    <main><header className="topbar"><Button variant="ghost" size="icon" className="menu" onClick={() => setMobileNav(v => !v)} aria-label="Menu"><Menu /></Button><div><div className="title-line"><h1>Vyťaženosť nabíjacích staníc</h1><span className="live"><i/>Živé dáta</span></div><p>Monitorovanie ZSE Drive · Dargov</p></div><div className="updated"><Activity /> Aktualizované {latest[0] ? fmtDate(Math.max(...latest.map(r => r.checkedAt))) : '—'}</div></header>
      <section className="workspace"><div className="filters"><label>Lokalita<NativeSelect value="dargov" disabled><NativeSelectOption value="dargov">Dargov</NativeSelectOption></NativeSelect></label><label>Stanica<NativeSelect value={station} onChange={e => setStation(e.target.value)}><NativeSelectOption value="all">Všetky</NativeSelectOption><NativeSelectOption value="73151">Ultra 1</NativeSelectOption><NativeSelectOption value="72182">Ultra 2</NativeSelectOption></NativeSelect></label><label>Od<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>Do<input type="date" value={to} onChange={e => setTo(e.target.value)} /></label><label>Stav konektora<NativeSelect value={status} onChange={e => setStatus(e.target.value)}><NativeSelectOption value="all">Všetky stavy</NativeSelectOption><NativeSelectOption value="available">Voľný</NativeSelectOption><NativeSelectOption value="occupied">Obsadený</NativeSelectOption><NativeSelectOption value="unavailable">Nedostupný</NativeSelectOption><NativeSelectOption value="unknown">Neznámy</NativeSelectOption></NativeSelect></label><Button onClick={load}><RefreshCw /> Obnoviť</Button><Button variant="outline" onClick={exportCsv}><Download /> Exportovať CSV</Button></div>{error && <div className="error"><AlertTriangle />{error}</div>}
        <section className="metrics"><Metric icon={Gauge} tone="#18a875" label="Priemerná vyťaženosť" value={`${Math.round(occupancy * 100)} %`} note={`${occupied.toLocaleString('sk-SK')} obsadených meraní`} /><Metric icon={PlugZap} tone="#15ad70" label="Aktuálne voľné" value={`${freeNow} / ${currentRows.length || 4}`} note="konektory k dispozícii" /><Metric icon={Clock3} tone="#188ae7" label="Priemerné nabíjanie" value={sessions.length ? fmtDuration(avgSession) : '—'} note={sessions.length ? `${sessions.length} dokončených relácií` : 'zatiaľ bez dokončenej relácie'} /><Metric icon={AlertTriangle} tone="#e94655" label="Nedostupnosť" value={`${(unavailability * 100).toFixed(1).replace('.', ',')} %`} note={`${unavailable.toLocaleString('sk-SK')} nedostupných meraní`} /></section>
        <section className="dashboard-grid"><article className="panel chart-panel"><div className="panel-title"><div><h2>Vyťaženosť podľa času</h2><p>0 = voľný · 0,5 = nedostupný/neznámy · 1 = obsadený</p></div><SlidersHorizontal /></div><div className="chart-wrap">{loading ? <div className="loading">Načítavam dáta…</div> : <ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData}><CartesianGrid stroke="#e9eef4" vertical={false}/><XAxis dataKey="label" tick={{fontSize:12,fill:'#728095'}}/><YAxis domain={[0,1]} ticks={[0,.5,1]} tickFormatter={v => v === 0 ? 'Voľný' : v === 1 ? 'Obsadený' : 'Mimo'} tick={{fontSize:12,fill:'#728095'}} width={78}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid #dfe7ef'}}/><Area type="stepAfter" dataKey={connectorKeys[0]} stroke="none" fill="#dff5ec" fillOpacity={.35}/>{connectorKeys.map((key, i) => <Line key={key} type="stepAfter" dataKey={key} name={`${stationLabel(Number(key.split('-')[0]))} · CCS ${key.split('-')[1]}`} stroke={COLORS[i % COLORS.length]} strokeWidth={2} dot={false} connectNulls/>)}</ComposedChart></ResponsiveContainer>}</div><div className="legend">{connectorKeys.map((key,i)=><span key={key}><i style={{background:COLORS[i%COLORS.length]}}/>{stationLabel(Number(key.split('-')[0]))} · CCS {key.split('-')[1]}</span>)}</div></article>
          <article className="panel current-panel"><div className="panel-title"><div><h2>Aktuálny stav</h2><p>{currentRows.length} konektory</p></div><BatteryCharging /></div><div className="connector-list">{currentRows.map(row => <div className="connector" key={row._id}><span className="charger"><PlugZap /></span><div><strong>{stationLabel(row.stationId)} · CCS {row.connectorId}</strong><small>{row.address.split(',')[1]?.trim() || 'Dargov'} · EVSE {row.evseId}</small></div><StatusPill status={statusOf(row.rawState)} /></div>)}</div></article>
          <article className="panel heat-panel"><div className="panel-title"><div><h2>Najvyťaženejšie časy</h2><p>Podiel obsadených meraní podľa dňa a hodiny</p></div><CalendarDays /></div><div className="hours">{Array.from({length:12},(_,i)=><span key={i}>{i*2}</span>)}</div><div className="heatmap">{heatmap.map((line,d)=><div className="heat-row" key={days[d]}><b>{days[d]}</b>{line.map((value,h)=><i key={h} title={`${days[d]} ${h}:00 · ${value == null ? 'bez dát' : Math.round(value*100)+' %'}`} style={{background:value == null?'#eef2f6':value<.2?'#21ad7a':value<.4?'#83d66e':value<.6?'#f4cd4d':value<.8?'#ff8b35':'#ef3e45'}}/>)}</div>)}</div><div className="heat-legend"><span><i style={{background:'#21ad7a'}}/>0–20 %</span><span><i style={{background:'#83d66e'}}/>20–40 %</span><span><i style={{background:'#f4cd4d'}}/>40–60 %</span><span><i style={{background:'#ff8b35'}}/>60–80 %</span><span><i style={{background:'#ef3e45'}}/>80–100 %</span><span><i style={{background:'#eef2f6'}}/>bez dát</span></div></article>
          <article className="panel changes-panel"><div className="panel-title"><div><h2>História zmien</h2><p>Posledné zmeny stavu vo vybranom období</p></div><History /></div><div className="table-scroll"><table><thead><tr><th>Čas</th><th>Stanica</th><th>Konektor</th><th>Predchádzajúci stav</th><th>Nový stav</th><th>Trvanie</th></tr></thead><tbody>{changes.slice(0,8).map(({row,before,after,duration})=><tr key={row._id}><td>{fmtDate(row.checkedAt)}</td><td>{stationLabel(row.stationId)}</td><td>CCS {row.connectorId}</td><td><StatusPill status={before}/></td><td><StatusPill status={after}/></td><td>{fmtDuration(duration)}</td></tr>)}{!changes.length&&<tr><td colSpan={6} className="empty">V tomto období zatiaľ nebola zaznamenaná zmena stavu.</td></tr>}</tbody></table></div></article></section>
      </section></main></div>;
}
